// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  id,
  created_at,
  updated_at,
  company_name,
  title,
  description,
  languages,
  created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at, updated_at, company_name, title, description, languages, created_by
`

type CreateJobParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompanyName string
	Title       string
	Description string
	Languages   []string
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompanyName,
		arg.Title,
		arg.Description,
		pq.Array(arg.Languages),
		arg.CreatedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyName,
		&i.Title,
		&i.Description,
		pq.Array(&i.Languages),
		&i.CreatedBy,
	)
	return i, err
}

const deleteJobByID = `-- name: DeleteJobByID :exec
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJobByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteJobByID, id)
	return err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, created_at, updated_at, company_name, title, description, languages, created_by FROM jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyName,
		&i.Title,
		&i.Description,
		pq.Array(&i.Languages),
		&i.CreatedBy,
	)
	return i, err
}

const getJobs = `-- name: GetJobs :many
SELECT id, created_at, updated_at, company_name, title, description, languages, created_by from jobs
`

func (q *Queries) GetJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyName,
			&i.Title,
			&i.Description,
			pq.Array(&i.Languages),
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
